[Uplay]
Name = ""
Saves = "V:\\Games\\Assassin's Creed Rogue\\Saves"
CdKeys = [""]
Language = "en-US"
OfflineMode = true
InstallHooks = false

[Uplay.Log]
Write = true
Path = ""

[Uplay.Profile]
AccountId = "JosephSeed"
Email = "fuck.ubisoft@stopoutposts.com"
Username = "JosephSeed"
Password = "123456"
Ticket = ""